-- ============================================
-- MIGRATION 018: Organization PowerBI Reports
-- ============================================
-- Creates table for storing organization-specific PowerBI report instances.
-- Each organization has copies of the template reports in their own workspace,
-- with unique report IDs generated by PowerBI.

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- ORGANIZATION_POWERBI_REPORTS
-- ============================================
-- Stores the deployed PowerBI report instances for each organization.
-- When reports are copied from the master template workspace to an
-- organization's workspace, PowerBI generates new report IDs.

CREATE TABLE IF NOT EXISTS organization_powerbi_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Organization Reference
  organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE NOT NULL,

  -- Template Reference
  template_report_id UUID REFERENCES powerbi_reports(id) ON DELETE CASCADE NOT NULL,

  -- PowerBI Identifiers
  powerbi_report_id TEXT NOT NULL, -- The actual PowerBI report GUID in the org's workspace
  powerbi_workspace_id TEXT NOT NULL, -- The organization's PowerBI workspace GUID

  -- Report Details (copied from template at deployment time)
  name TEXT NOT NULL, -- Report name in PowerBI
  display_name TEXT, -- Human-readable display name
  description TEXT,

  -- Deployment Status
  deployment_status TEXT DEFAULT 'pending', -- 'pending', 'active', 'failed', 'archived'
  deployment_error TEXT, -- Error message if deployment failed
  deployed_at TIMESTAMPTZ, -- When the report was successfully deployed
  deployed_by TEXT, -- Email of user who deployed it

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Ensure each organization has unique report instances
  UNIQUE(organization_id, template_report_id),
  UNIQUE(organization_id, powerbi_report_id)
);

COMMENT ON TABLE organization_powerbi_reports IS 'Deployed PowerBI report instances for each organization - maps template reports to org-specific copies';
COMMENT ON COLUMN organization_powerbi_reports.organization_id IS 'Which organization owns this report instance';
COMMENT ON COLUMN organization_powerbi_reports.template_report_id IS 'References the master template report';
COMMENT ON COLUMN organization_powerbi_reports.powerbi_report_id IS 'Actual PowerBI report GUID in the organization workspace';
COMMENT ON COLUMN organization_powerbi_reports.powerbi_workspace_id IS 'PowerBI workspace GUID where this report is deployed';
COMMENT ON COLUMN organization_powerbi_reports.deployment_status IS 'Current status: pending, active, failed, or archived';
COMMENT ON COLUMN organization_powerbi_reports.deployed_at IS 'Timestamp when report was successfully deployed';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_org_reports_organization ON organization_powerbi_reports(organization_id);
CREATE INDEX IF NOT EXISTS idx_org_reports_template ON organization_powerbi_reports(template_report_id);
CREATE INDEX IF NOT EXISTS idx_org_reports_status ON organization_powerbi_reports(deployment_status);
CREATE INDEX IF NOT EXISTS idx_org_reports_powerbi_id ON organization_powerbi_reports(powerbi_report_id);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_organization_powerbi_reports_updated_at ON organization_powerbi_reports;
CREATE TRIGGER update_organization_powerbi_reports_updated_at
  BEFORE UPDATE ON organization_powerbi_reports
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- SUCCESS MESSAGE
-- ============================================

DO $$
BEGIN
  RAISE NOTICE 'Migration 018 completed successfully!';
  RAISE NOTICE '✓ Created organization_powerbi_reports table';
  RAISE NOTICE '✓ Added indexes for fast lookups';
  RAISE NOTICE '✓ Added triggers for updated_at';
  RAISE NOTICE '';
  RAISE NOTICE 'Next steps:';
  RAISE NOTICE '1. Deploy template reports to organization workspaces';
  RAISE NOTICE '2. Record the new PowerBI report IDs in this table';
  RAISE NOTICE '3. Update embed token API to use org-specific report IDs';
END $$;
